package dex.poke;

import java.util.HashMap;

public class PokeGenOne extends PokeDexMain{
    HashMap<Integer, String> gen1;

    PokeGenOne() {
        super();

        kanto();
    }

    private void kanto() {
        gen1 = new HashMap<>();

        gen1.put(1, "Bulbasaur");
        gen1.put(2, "Ivysaur");
        gen1.put(3, "Venusaur");
        gen1.put(4, "Charmander");
        gen1.put(5, "Charmeleon");
        gen1.put(6, "Charizard");
        gen1.put(7, "Squirtle");
        gen1.put(8, "Wartortle");
        gen1.put(9, "Blastoise");
        gen1.put(10, "Caterpie");
        gen1.put(11, "Metapod");
        gen1.put(12, "Butterfree");
        gen1.put(13, "Weedle");
        gen1.put(14, "Kakuna");
        gen1.put(15, "Beedrill");
        gen1.put(16, "Pidgey");
        gen1.put(17, "Pidgeotto");
        gen1.put(18, "Pidgeot");
        gen1.put(19, "Rattata");
        gen1.put(20, "Raticate");
        gen1.put(21, "Spearow");
        gen1.put(22, "Fearow");
        gen1.put(23, "Ekans");
        gen1.put(24, "Arbok");
        gen1.put(25, "Pikachu");
        gen1.put(26, "Raichu");
        gen1.put(27, "Sandshrew");
        gen1.put(28, "Sandslash");
        gen1.put(29, "Nidoran F");
        gen1.put(30, "Nidorina");
        gen1.put(31, "Nidoqueen");
        gen1.put(32, "Nidoran M");
        gen1.put(33, "Nidorino");
        gen1.put(34, "Nidoking");
        gen1.put(35, "Clefairy");
        gen1.put(36, "Clefable");
        gen1.put(37, "Vulpix");
        gen1.put(38, "Ninetales");
        gen1.put(39, "Jigglypuff");
        gen1.put(40, "Wiggytuff");
        gen1.put(41, "Zubat");
        gen1.put(42, "Golbat");
        gen1.put(43, "Oddish");
        gen1.put(44, "Gloom");
        gen1.put(45, "Vileplume");
        gen1.put(46, "Paras");
        gen1.put(47, "Parasect");
        gen1.put(48, "Venonat");
        gen1.put(49, "Venomoth");
        gen1.put(50, "Diglett");
        gen1.put(51, "Dugtrio");
        gen1.put(52, "Meowth");
        gen1.put(53, "Persian");
        gen1.put(54, "Psyduck");
        gen1.put(55, "Golduck");
        gen1.put(56, "Mankey");
        gen1.put(57, "Primeape");
        gen1.put(58, "Growlithe");
        gen1.put(59, "Arcanine");
        gen1.put(60, "Poliwag");
        gen1.put(61, "Poliwhirl");
        gen1.put(62, "Poliwrath");
        gen1.put(63, "Abra");
        gen1.put(64, "Kadabra");
        gen1.put(65, "Alakazam");
        gen1.put(66, "Machop");
        gen1.put(67, "Machoke");
        gen1.put(68, "Machamp");
        gen1.put(69, "Bellsprout");
        gen1.put(70, "Weepinbell");
        gen1.put(71, "Victreebel");
        gen1.put(72, "Tentacool");
        gen1.put(73, "Tentacruel");
        gen1.put(74, "Geodude");
        gen1.put(75, "Graveler");
        gen1.put(76, "Golem");
        gen1.put(77, "Ponyta");
        gen1.put(78, "Rapidash");
        gen1.put(79, "Slowpoke");
        gen1.put(80, "Slowbro");
        gen1.put(81, "Magnemite");
        gen1.put(82, "Megneton");
        gen1.put(83, "Farfetch'd");
        gen1.put(84, "Doduo");
        gen1.put(85, "Dodrio");
        gen1.put(86, "Seel");
        gen1.put(87, "Dewgong");
        gen1.put(88, "Grimer");
        gen1.put(89, "Muk");
        gen1.put(90, "Shellder");
        gen1.put(91, "Cloyster");
        gen1.put(92, "Gastly");
        gen1.put(93, "Haunter");
        gen1.put(94, "Gengar");
        gen1.put(95, "Onix");
        gen1.put(96, "Drowzee");
        gen1.put(97, "Hypno");
        gen1.put(98, "Krabby");
        gen1.put(99, "Kingler");
        gen1.put(100, "Voltorb");
        gen1.put(101, "Electrode");
        gen1.put(102, "Exeggcute");
        gen1.put(103, "Exeggutor");
        gen1.put(104, "Cubone");
        gen1.put(105, "Marowak");
        gen1.put(106, "Hitmonlee");
        gen1.put(107, "Hitmonchan");
        gen1.put(108, "Lickitung");
        gen1.put(109, "Koffing");
        gen1.put(110, "Weezing");
        gen1.put(111, "Rhyhorn");
        gen1.put(112, "Rhydon");
        gen1.put(113, "Chansey");
        gen1.put(114, "Tangela");
        gen1.put(115, "Kangaskhan");
        gen1.put(116, "Horsea");
        gen1.put(117, "Seadra");
        gen1.put(118, "Goldeen");
        gen1.put(119, "Seaking");
        gen1.put(120, "Staryu");
        gen1.put(121, "Starmie");
        gen1.put(122, "Mr. Mime");
        gen1.put(123, "Scyther");
        gen1.put(124, "Jynx");
        gen1.put(125, "Electabuzz");
        gen1.put(126, "Magmar");
        gen1.put(127, "Pinsir");
        gen1.put(128, "Tauros");
        gen1.put(129, "Magikarp");
        gen1.put(130, "Gyarados");
        gen1.put(131, "Lapras");
        gen1.put(132, "Ditto");
        gen1.put(133, "Eevee");
        gen1.put(134, "Vaporeon");
        gen1.put(135, "Jolteon");
        gen1.put(136, "Flareon");
        gen1.put(137, "Porygon");
        gen1.put(138, "Omanyte");
        gen1.put(139, "Omastar");
        gen1.put(140, "Kabuto");
        gen1.put(141, "Kabutops");
        gen1.put(142, "Aerodactyl");
        gen1.put(143, "Snorlax");
        gen1.put(144, "Articuno");
        gen1.put(145, "Zapdos");
        gen1.put(146, "Moltres");
        gen1.put(147, "Dratini");
        gen1.put(148, "Dragonair");
        gen1.put(149, "Dragonite");
        gen1.put(150, "Mewtwo");
        gen1.put(151, "Mew");
    }
}
